services:
  - type: web
    name: food-costs
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile && bundle exec rake assets:clean"
    startCommand: "bundle exec rake db:migrate && bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: food-costs-db
          property: connectionString
    healthCheckPath: /up

databases:
  - name: food-costs-db
    databaseName: food_costs_production
    user: food_costs_user
    plan: free 